CREATE DATABASE IF NOT EXISTS db_wt;

USE db_wt;

CREATE TABLE IF NOT EXISTS HORSE (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    wins INT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS RACE (
    id INT NOT NULL AUTO_INCREMENT,
    `date` DATE NOT NULL,
    winnerId INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(winnerId) REFERENCES HORSE (id)
);

CREATE TABLE IF NOT EXISTS BET (
    id INT NOT NULL AUTO_INCREMENT,
    user VARCHAR(255) NOT NULL,
    raceId INT NOT NULL,
    horseId INT NOT NULL,
    sum INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(raceId) REFERENCES RACE (id),
    FOREIGN KEY(horseId) REFERENCES HORSE (id)
);